# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: testdb
  pool: 5
  username: consultadd
  password: consultadd   ### password you have specified within psql
  host: localhost
  port: 5432  
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: testdb
  pool:     5
  template: template0

